### ISSUE TITLE
[Gloabal] Improvement interface

### ISSUE THREAD

**Issue by Septdir** [SeptdirWorkshop/jYProExtra#11]
* Delete unnecessary settings (child), the functions themselves must be enabled constantly
* Leave only one fieldset
* Improve names and descriptions of settings

**Comment by b2z** [comment]
Поправки по языковым файлам, что на что поменять:

Удаление JavaScripts
на
Удаление JavaScript

not displaying the modules
на
not displaying modules

overriding layouts
на
layout overrides

connecting language files
на
language files include

Removing JavaScripts
на
Remove JavaScript

builder YOOtheme Pro
на
YOOtheme Pro builder

Material
на
Article

Favorites
на
Featured
