### ISSUE TITLE
Добавить поддержку AdvancedModuleMnager

### ISSUE THREAD

**Issue by kernusr** [SeptdirWorkshop/jYProExtra#2]
В квикстарате стоит com_advancedmodules
С ним не работает переопределение макетов модулей.

**Comment by kernusr** [comment]
`$formName == 'com_advancedmodules.module'`
Для AdvancedModuleMnager

**Comment by Septdir** [comment]
Version with enhancement
[plg_system_jyproextra_1.0.1-dev.zip](https://github.com/SeptdirWorkshop/JYProExtra/files/3103045/plg_system_jyproextra_1.0.1-dev.zip)
