### ISSUE TITLE
Wrong links in Toolbar for installations in subdirectories

### ISSUE THREAD

**Issue by forrestkirby** [SeptdirWorkshop/jYProExtra#24]
First of all, thank you very much for developing this useful extension!

**Description**
The link to access the Builder and Customizer in the frontend leads to the directory `administrator/` in the root directory of the webspace, which is not where the admin directory is located if the CMS has been installed in a sub-directory.

**Steps to reproduce**
1. Install Joomla in a sub-directory, not the root folder.
2. Install the plugin.
3. Activate the option *Toolbar*.
4. Visit the frontend.
5. Click on the toolbar link.

**Expected behavior**
YOOtheme Pro Builder and Customizer opens.

**Screenshots**

![](http://snap.ashampoo.com/uploads/2019-10-12/qrty1jOw47QCVunkfsyJQ03nba982mum7IFYsuPOSbRJV0u2snFDMcrocqM75BK2.png)

![](http://snap.ashampoo.com/uploads/2019-10-12/VV9KhuPP8OB9Lr5qHVhYRFPsyxxL7n7ue5alRq2Q06PlOn3wDDqVJbjCybOwOMLS.png)

**System Information (please complete the following information):**
 - Extension version: 1.3.0
 - PHP version: 7.3.6
 - Joomla! version: 3.9.12 Stable
 - Browser: Chrome

Best regards

**Comment by Septdir** [comment]
@forrestkirby You can fix this by replacing `$uri->toString(array('scheme', 'host', 'port'))` with `'https://example.com/subforlder'` on this line.
https://github.com/SeptdirWorkshop/jYProExtra/blob/master/jyproextra.php#L678

In the next version I will fix this bug
