### ISSUE TITLE
J! Breadcrumbs element will be deleted on update

### ISSUE THREAD

**Issue by forrestkirby** [SeptdirWorkshop/jYProExtra#25]
**Description**
The element `joomla_breadcrumbs` will be deleted on updating YOOtheme Pro as it is placed in the directory `/templates/yootheme/vendor/yootheme/builder-joomla/elements/` instead of a child theme directory.

**Steps to reproduce**
1. Install the plugin `plg_system_jyproextra_1.3.0`
2. Open the page builder and add a new *J! Breadcrumbs* element
3. Update YOOtheme Pro
4. The directory `/templates/yootheme/vendor/yootheme/builder-joomla/elements/joomla_breadcrumbs/` that contains the source files for the *J! Breadcrumbs* element have been deleted

**Expected behavior**
The source files for the *J! Breadcrumbs* element should still be present and the element should continue to work, unless there have been breaking changes for custom elements in YOOtheme Pro.

**Screenshots**
![](http://snap.ashampoo.com/uploads/2019-10-12/5K8AOUMrjnmJsroQX2Oll86IxeS9nGrKRqlbFyspg0YYQiKjDzUpySXqWLPfSBqf.png)

**System Information:**
- Extension version: 1.3.0
- PHP version: 7.3.6
- Joomla! version: 3.9.12 Stable
- Browser: Chrome

Thank you!

**Comment by Septdir** [comment]
You can fix this by reinstalling jYProExtra.
Just install jYProExtra on top of the existing version
In the next version I will fix this bug
