### ISSUE TITLE
Добавить возможность исключения модулей, для сторонних компонентов

### ISSUE THREAD

**Issue by kernusr** [SeptdirWorkshop/jYProExtra#26]
Столкнулся с необходимостью спрятать модули, в карточке джушоппинга. Было бы неплохо иметь такую возможность!
Однако, есть и проблема - если начать интегрировать плагин со всеми компонентами, то так никакого селекта не хватит (а если у меня компонент кастомный? Мне вообще форкать плаг придётся?)
Поэтому предлагаю немного иной подход:
Сделать список исключений - динамическим. По-умолчанию всё так же поставляются настройки для исключения из стандартных компонентов. Для всего остального - сделать настройку в самом плагине (сабформу), с двумя полями - название и представление. Таким образом, любой пользователь сможет настроить исключения для себя и не придётся городить кучу интеграций и следить за чужими компонентами

**upd**
Забыл, что ещё же и компонент проверять нужно. Поэтому можно сделать, либо третье поле "компоннет", либо, в представлении, записывать 
`com_{componentname}.{view}`

**Comment by kernusr** [comment]
Если делать одним полем, с разделителем, то и проверка вот тут https://github.com/SeptdirWorkshop/jYProExtra/blob/b91c7c456a5c0f59a10a97d2b541330883e0572f/jyproextra.php#L378, преобретёт вид

`elseif ($params->get('unset_content')
	&& in_array($component.'.'.$view, $params->get('unset_content')))
{
	$resetKeys = true;
	unset($modules[$key]);
}`

Для обратной совместимости, в принципе, можно же даже не удалять старое правило, а просто добаить ещё одно условие. ПОлучается, что у тех, кто имеет старые записи (только для com_content) будет отрабатывать всё как и раньше.
Вот только, что будет если, открыть модуль, сохранённый до обновления логики, а потом пересохранить с новой логикой. Получается, что настройки не запишутся, ибо таких значений в плагине уже не будет....

**Comment by kernusr** [comment]
Хм... из наблюдений - джумшоппинг не передаёт view. У него это дело можно по контроллеру отследить. Сие усложняет настройку динамически определяемых условий...

**Comment by Septdir** [comment]
Ну с joomshoping можно посмотреть, сами view там во всяком случае есть

К тому же я придумал как сделать поле на все компоненты сразу. И без необходимости вводить что-то руками

**Comment by Septdir** [comment]
[plg_system_jyproextra_1.3.2-dev.zip](https://github.com/SeptdirWorkshop/jYProExtra/files/3858680/plg_system_jyproextra_1.3.2-dev.zip)
