### ISSUE TITLE
Переопрелеение editor.css

### ISSUE THREAD

**Issue by kernusr** [SeptdirWorkshop/jYProExtra#32]
Установленный по-умолчанию в Joomla TinyMCE (а может и другие редакторы), поддерживает функцию переопределение/дополнения встроенных стилей.
Для переопределения, необходимо создать, в папке шаблона/css файлик editor.css и описать в нём желаемые стили. После этого они появятся в редакторе.

Проблема в том, что редактор не видит файл из дочерней темы yootheme.

Пример файла /templates/yootheme/css/editor.css:
`table.sales-table{
    border: 1px solid;
}`

Что я получаю после этого - видно на скриншоте
![Аннотация 2019-11-28 012941](https://user-images.githubusercontent.com/16020878/69763552-974a4580-117e-11ea-87f2-29dd4aafe92c.png)

**Comment by Septdir** [comment]
Посмотрим. Но не уверен что получится

**Comment by Septdir** [comment]
Не выйдет.
Там в каждом плагине идет просто обращение на базу данных.
Так что если только классы. плагинов переопределяясь, так-то не вариант.
