### ISSUE TITLE
Конфликт с DJ-Classifieds

### ISSUE THREAD

**Issue by Sulpher** [SeptdirWorkshop/jYProExtra#50]
Собственно, вот так выглядит DJ-Classifieds (список товаров категории) в нормальном виде:
![Screen Shot 2020-05-16 at 13 29 02](https://user-images.githubusercontent.com/3432048/82117565-7fd93600-9779-11ea-88d9-482ac80ddf77.png)

Теперь включаю в JyProExtra настройку:
Изображения
Данная функция позволяет использовать улучшение изображений YOOtheme Pro (webP, lazy load) на всем сайте.

![Screen Shot 2020-05-16 at 13 29 10](https://user-images.githubusercontent.com/3432048/82117578-98495080-9779-11ea-936b-51409793cea2.png)

И получаю вот такой результат:
![Screen Shot 2020-05-16 at 13 28 54](https://user-images.githubusercontent.com/3432048/82117581-9f705e80-9779-11ea-8d8f-89a31d76ad94.png)

Сравнил HTML код.

Вот обычное состояние: 

`<img src="/components/com_djclassifieds/images/item/3/prodam-starnnye-serebryannye-monety_7242_1_ths.jpg" class="Tips1" title="" rel="<div class='tp_desc'>Продаю дешево серебреные монеты прошлый век. Не битые и не гнутые полтинники. Остатки большой коллекции, отборные экземпляры и коллекционная сохранность. Четко видно клеймо ПЛ на гурте. Чеканка монетный двор Петроград. Пять монет серебряные полтинники. 4 монеты (звезда) 1922 г. и 1 монета (кузнец с молотом) 1924 г. Продаю все без торга за 5500 р. ...</div><div style='clear:both'></div><div class='title'>Изображения</div><div class='images_box'><img src='/components/com_djclassifieds/images/item/3/prodam-starnnye-serebryannye-monety_7242_1_ths.jpg' /><img src='/components/com_djclassifieds/images/item/3/prodam-starnnye-serebryannye-monety_7242_2_ths.jpg' /></div><div style='clear:both'></div>" alt="Продам старнные серебрянные монеты">`

А вот после включения параметра в JyProExtra:

`		<img class="Tips1" title="" uk-img="" alt="" data-src="/templates/yootheme/cache/prodam-starnnye-serebryannye-monety_7242_1_ths-351f18b7.webp" data-srcset="/templates/yootheme/cache/prodam-starnnye-serebryannye-monety_7242_1_ths-351f18b7.webp 56w" data-sizes="(min-width: 56px) 56px" data-width="56" data-height="32" sizes="(min-width: 56px) 56px" srcset="/templates/yootheme/cache/prodam-starnnye-serebryannye-monety_7242_1_ths-351f18b7.webp 56w" src="https://домен.ru/templates/yootheme/cache/prodam-starnnye-serebryannye-monety_7242_1_ths-351f18b7.webp">Продаю дешево серебреные монеты прошлый век. Не битые и не гнутые полтинники. Остатки большой коллекции, отборные экземпляры и коллекционная сохранность. Четко видно клеймо ПЛ на гурте. Чеканка монетный двор Петроград. Пять монет серебряные полтинники. 4 монеты (звезда) 1922 г. и 1 монета (кузнец с молотом) 1924 г. Продаю все без торга за 5500 р.  .</a></div>`

Плагин режет rel="", в котортом авторы компонента запихали  код.
тут вариант: либо пилить формирование тултпипа в шаблоне компонента, либо в плагине добавить поле для исключения компонентов к обработке (ручками вводим com_djclassifieds).

**Comment by Septdir** [comment]
Эм. html код в атрибуте.   
Это как-то перебор, да и не валидно.
Вставлять в атрибут html по себе не валидно и вызывает множество проблем, к тому же rel применяться к `link`, `a`, `area`, и `form`, но ни как не к img.

Поэтому счесть это багом jYProExtra не могу.

Так же не вижу смысла добавлять к функции задача которой обрабатывать изображения на всем сайте, опцию исключение в каких либо компонентах.

Могу предложить 3 варианта.
1. Исправить шаблон, чтобы такого там не было.
2. Не обрабатывать эти изображения испольная один из следующий атрибутов  `no-lazy`, `no-handler` Но не уверен что плагин в принципе сможет увидеть плавильное закрытие тега.
3. Не использовать данную функцию.

Посмотрел на демо dj classfield и не нашел там такого.
