### ISSUE TITLE
Проблема с переопределением размеров картинок

### ISSUE THREAD

**Issue by alex-revo** [SeptdirWorkshop/jYProExtra#61]
**Опишите ошибку**
Начиная с версии Yootheme Pro 2.3 логика работы темы и плагина отличается, что приводит к нарушению размеров изображений.

**Как воспроизвести**
Шаги для воспроизведения ошибки:
Вся суть описана здесь: https://yootheme.com/support/question/141351

**Ожидаемое поведение**
Верни все как было)

**Дополнительный контекст**
В общем нужно проверить переопределения, вероятно нужно обновить алгоритмы.

**Comment by Septdir** [comment]
[plg_system_jyproextra_1.6.3-dev.zip](https://github.com/SeptdirWorkshop/jYProExtra/files/5481348/plg_system_jyproextra_1.6.3-dev.zip)
