### ISSUE TITLE
Split cache for webp also into amp

### ISSUE THREAD

**Issue by Notebit** [SeptdirWorkshop/jYProExtra#64]
I use jYProExtra for serving two different caches to browsers supporting webp and not supporting webp. It works perfectly but now i am making an amp version of the pages with Jamp and I have the problem again.
The output is exactly the same as the page generated by Yootheme Pro with a search and replace of some tags with amp tags, so maybe there is some smart and easy way to add support for the split cache for amp into the plugin

**Comment by Septdir** [comment]
Well, suppose I can add readings somehow additional parameter. For example (array) 'ext_cache_key' but you start adding it somehow to application-> input

**Comment by Notebit** [comment]
I don't think it is needed
the plugin I use for amp is called Jamp, is one of the mostly used together with Yootheme Pro, and it supports a call for detecting if the page is amp JAmpHelper::$isJAmpRequest
like this
`if(class_exists('JAmpHelper') && JAmpHelper::$isJAmpRequest) {`

it should work, but I am not totally sure cause Jamp has its own caching as well

**Comment by Notebit** [comment]
considering that jamp has it's own cache, I am trying to split the amp cache for webp into jamp. I think it is the best approach instead adding it with an external plugin.
thanks for your prompt reply
