### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by alex-revo** [SeptdirWorkshop/jYProExtra#71]
**Опишите ошибку**
Uncaught TypeError: Cannot read property 'appendChild' of null
    at XMLHttpRequest.request.onreadystatechange (customizer.min.js?3b0f2fcd88fd3b2047a25142e730e06e:1

**Как воспроизвести**
Шаги для воспроизведения ошибки:
Обнови тему до 2.4.11 и открой консоль в билдере.
Видимо что-то поменяли в отображении сайдбара билдера.

**Comment by Septdir** [comment]
Включи, пожалуйста, отладку сайта и посмотри на какой именно строчке.

**Comment by alex-revo** [comment]
32 строка
// Add modal
	let content = document.createElement('div');
	content.innerHTML = response.data[0].content;
→ 	document.querySelector('body .uk-noconflict').appendChild(content.firstChild);

**Comment by Septdir** [comment]
Пофикшено уже.
https://github.com/SeptdirWorkshop/jYProExtra/commit/826fb7c340b3187032e04adfc4a4caf4b50ccc26#diff-86cc7e296ea864c9012c70916e8978a0a3f09d6f3473937555e19a8dff697927

https://github.com/SeptdirWorkshop/jYProExtra/blob/master/media/js/customizer.js#L32
