### ISSUE TITLE
Get rid of ajax image caching in frontend

### ISSUE THREAD

**Issue by Notebit** [SeptdirWorkshop/jYProExtra#72]
Yootheme pro uses an ajax link instead of the real image the first time the page is loaded, I guess the purpose is to add the image to Yootheme cache. I tried to disable uk-img and srcset in my override, but I still get the ajax link.

The problem is that if you have Joomla cache enabled (maybe it is the same also in wordpress), the ajax link instead of the image is served until the cache expires. If you have a very busy website and you set the cache time to a quite long time, then the ajax link is served for long time.
Is there any way to move this task of caching the image to backend when the content is created instead of using frontend for it?

having an ajax call in the image src instead of an actual link to a static file creates any kind of troubles with search bots, amp plugins and so on.

If we are able to cache the requested images into Yootheme cache in backend, for example when a new article is saved, then I guess that Yootheme pro will use directly the images in the cache as src instead of using ajax links, so  we would solve the problem

**Comment by Septdir** [comment]
Fixed in YooThemePro 3.0
