### ISSUE TITLE
Fatal error: Cannot declare class Joomla\CMS\HTML\HTMLHelper

### ISSUE THREAD

**Issue by rvalitov** [SeptdirWorkshop/jYProExtra#73]
**Describe the bug**
Joomla frontend fails to load with error:

Fatal error: Cannot declare class Joomla\CMS\HTML\HTMLHelper, because the name is already in use in /var/www/xxx/web/plugins/system/jyproextra/classes/HTMLHelper.php on line 0

**System Information (please complete the following information):**
 - Extensions version 1.7.1
 - PHP version: 7.4.26
 - Joomla 3.10.4
 - Yootheme Pro 2.7.11

**Comment by Septdir** [comment]
This error appears when some component or plugin tries to redefine the HTMLHelper again.

Turn on debug mode and see what solution is trying to do this, but most likely you will not be able to use the child themes functions in jYProExtra plugin
