### ISSUE TITLE
There is no "plg_system_extrapro.administrator.config" asset of a "script" type in the registry.

### ISSUE THREAD

**Issue by alex-revo** [SeptdirWorkshop/jYProExtra#80]
**Опишите ошибку**
При открытии параметров плагина - ошибка 500

**Скриншоты**
![image](https://github.com/SeptdirWorkshop/jYProExtra/assets/7030604/bead2b0b-c243-4710-8e28-b40e225a6c18)

**Информация о системе (пожалуйста, заполните следующую информацию):**
  - Версия Расширения 1.0.0 - скачал из ветки и установил
  - Версия PHP: 8,1,26
  - ОС сСрвера: Linux

**Comment by Septdir** [comment]
Ты не в ту репу issue сделал и какая joomla?

**Comment by Septdir** [comment]
Скорее всего это из-за того что ты скачал ветку а не релиз.
